repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.fwf$
      - id: end-of-file-fixer
        exclude: \.fwf$
      - id: check-yaml
      - id: check-added-large-files


  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: \.fwf$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: \.fwf$

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [pre-push]
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
